@echo off

del *.obj /f/s/q
del *.ncb /f/s/q
del *.opt /f/s/q
del *.aps /f/s/q
del *.plg /f/s/q
del *.bsc /f/s/q
del *.sbr /f/s/q
del *.idb /f/s/q
del *.ilk /f/s/q
del *.pdb /f/s/q
del *.gid /f/s/q
del *.pch /f/s/q
del *.tli /f/s/q
del *.tlh /f/s/q
del *.res /f/s/q
echo.---------------------------------------------------------------------------
echo. 					Done.
echo.---------------------------------------------------------------------------
